import { Product } from "@/types";

export const PRODUCTS: Product[] = [
  // CHECKMATE COLLECTION
  {
    id: "cm-01",
    name: "CHESS NOT CHECKERS TEE",
    slug: "chess-not-checkers-tee",
    collection: "checkmate",
    category: "tee",
    price: 85,
    image: "/assets/photography/p1.png",
    lifestyleImage: "/assets/photography/p19.png",
    gsm: "280 GSM",
    fabric: "100% Combed Heavy Cotton",
    color: "Washed Void Black / Bullion Gold",
    edition: "Drop 001 // Edition of 300",
    description:
      "Crafted with calculated poise. Featuring the iconic King's Gambler artwork screenprinted with high-density bullion gold ink over 280 GSM pre-shrunk cotton.",
    details: [
      "280 GSM heavyweight carded jersey",
      "High-density discharge screenprint with gold foil accents",
      "Reinforced double-needle collar stitch",
      "Custom woven MW Knight hem label",
      "Pre-washed vintage patina finish",
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "cm-02",
    name: "CHESS NOT CHECKERS HOODIE",
    slug: "chess-not-checkers-hoodie",
    collection: "checkmate",
    category: "hoodie",
    price: 175,
    image: "/assets/photography/p2.png",
    lifestyleImage: "/assets/photography/p20.png",
    gsm: "450 GSM",
    fabric: "Heavyweight French Terry",
    color: "Pitch Black / Bullion Gold",
    edition: "Drop 001 // Limited Edition",
    description:
      "Uncompromising armor. 450 GSM custom-milled French terry fleece engineered with structural drop shoulders and tactile gold embroidery.",
    details: [
      "450 GSM luxury unbrushed French terry",
      "Double-layered crossover hood with no drawstrings",
      "Front kangaroo pocket with bar-tack reinforcement",
      "Ribbed side gussets for fluid motion",
      "Custom MW diamond crest sleeve print",
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "cm-03",
    name: "CHESS NOT CHECKERS LONGSLEEVE",
    slug: "chess-not-checkers-longsleeve",
    collection: "checkmate",
    category: "longsleeve",
    price: 110,
    image: "/assets/photography/p3.png",
    lifestyleImage: "/assets/photography/p17.png",
    gsm: "300 GSM",
    fabric: "100% Interlock Cotton",
    color: "Void Black / Gold Print",
    edition: "Drop 001 // Edition of 250",
    description:
      "Strategic elegance. Full sleeve coverage with reinforced 1x1 rib cuffs and high-impact back and front typography.",
    details: [
      "300 GSM compact interlock cotton",
      "Oversized boxy architectural silhouette",
      "Taped shoulder-to-shoulder interior seam",
      "Distress-resistant gold plastisol cure",
    ],
    inStock: true,
  },
  {
    id: "cm-04",
    name: "MW KNIGHT CREST TEE",
    slug: "mw-knight-crest-tee",
    collection: "checkmate",
    category: "tee",
    price: 80,
    image: "/assets/photography/p14.png",
    lifestyleImage: "/assets/photography/p21.png",
    gsm: "280 GSM",
    fabric: "100% Combed Cotton",
    color: "Monochrome Black / Chalk White",
    edition: "Drop 001 // Archive Core",
    description:
      "Precision emblem. Minimalist circular chess knight anchored by the signature geometric diamond hallmark.",
    details: [
      "280 GSM heavyweight jersey",
      "Crisp zero-hand waterbase print",
      "Slightly elongated streetwear drop hem",
      "Woven nape label with gold chess coordinates",
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "cm-05",
    name: "GOLD CROWN ARCH TEE",
    slug: "gold-crown-arch-tee",
    collection: "checkmate",
    category: "tee",
    price: 80,
    image: "/assets/photography/p15.png",
    lifestyleImage: "/assets/photography/p23.png",
    gsm: "280 GSM",
    fabric: "100% Combed Cotton",
    color: "Matte Black / Bullion Gold",
    edition: "Drop 001 // Limited Run",
    description:
      "Subtle supremacy. A clean arched Checkmate wordmark crowned by royal finials in pure bullion pigment.",
    details: [
      "280 GSM luxury combed cotton",
      "Matte gold discharge print that softens with wash",
      "Pre-shrunk for permanent streetwear proportions",
    ],
    inStock: true,
  },
  {
    id: "cm-06",
    name: "RED DRIP GRAFFITI TEE",
    slug: "red-drip-graffiti-tee",
    collection: "checkmate",
    category: "tee",
    price: 85,
    image: "/assets/photography/p16.png",
    lifestyleImage: "/assets/photography/p22.png",
    gsm: "280 GSM",
    fabric: "100% Combed Cotton",
    color: "Deep Black / Crimson Drip",
    edition: "Drop 001 // Night Ops",
    description:
      "Controlled aggression. Hand-drawn graffiti script with authentic paint splatters in saturated crimson.",
    details: [
      "280 GSM heavyweight cotton",
      "Screenprinted in blood crimson ink with matte seal",
      "Sleeve MW knight diamond stamp",
      "Tailored streetwear fit",
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "cm-07",
    name: "SHOWROOM CAPSULE 001",
    slug: "showroom-capsule-001",
    collection: "checkmate",
    category: "capsule",
    price: 340,
    originalPrice: 420,
    image: "/assets/photography/p18.png",
    lifestyleImage: "/assets/photography/p23.png",
    gsm: "Multi-GSM",
    fabric: "Curated French Terry & Cotton Set",
    color: "Black / Gold / Diamond / White",
    edition: "Collector Box Set // 50 Units",
    description:
      "The definitive Checkmate inauguration bundle: Includes the Chess Hoodie, Knight Crest Tee, Gold Crown Tee, and embroidered Snapback in a custom matte-black presentation box.",
    details: [
      "1x Chess Not Checkers Hoodie (450 GSM)",
      "1x MW Knight Crest Tee (280 GSM)",
      "1x Gold Crown Arch Tee (280 GSM)",
      "1x Embroidered Wool Blend Snapback",
      "Numbered certificate of authenticity",
    ],
    inStock: true,
  },

  // EMOTIONS COLLECTION ("NO EMOTIONS. ONLY MOTION.")
  {
    id: "em-01",
    name: "THREE APES OVERSIZED TEE",
    slug: "three-apes-oversized-tee",
    collection: "emotions",
    category: "tee",
    price: 85,
    image: "/assets/photography/p5.png",
    lifestyleImage: "/assets/photography/p24.png",
    gsm: "280 GSM",
    fabric: "100% Ring-spun Heavy Cotton",
    color: "Carbon Black / Red / Acid Gold",
    edition: "Drop 001 // Motion State",
    description:
      "Blind to distraction. Hear no evil, see no emotion. Triple primates with metallic gold visor strikes across optic white typography.",
    details: [
      "280 GSM ring-spun cotton jersey",
      "Multi-pass screenprint with high-voltage red block typography",
      "Slightly dropped shoulders with wide sleeve opening",
      "Hem woven label: 'BUILT DIFFERENT / MADE TO LEAD'",
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "em-02",
    name: "THREE APES VELOCITY HOODIE",
    slug: "three-apes-velocity-hoodie",
    collection: "emotions",
    category: "hoodie",
    price: 175,
    image: "/assets/photography/p6.png",
    lifestyleImage: "/assets/photography/p26.png",
    gsm: "450 GSM",
    fabric: "Heavyweight French Terry",
    color: "Deep Void Black / Red / Gold",
    edition: "Drop 001 // Limited Run",
    description:
      "Instinctive heat. 450 GSM dense French terry featuring the Three Apes composition on chest with heavy ribbing.",
    details: [
      "450 GSM custom knit cotton fleece",
      "Substantial oversized drape with structured hood",
      "High-density ink resistant to cracking and wash wear",
      "Concealed media pocket inside kangaroo pouch",
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "em-03",
    name: "NO EMOTION LONGSLEEVE",
    slug: "no-emotion-longsleeve",
    collection: "emotions",
    category: "longsleeve",
    price: 110,
    image: "/assets/photography/p7.png",
    lifestyleImage: "/assets/photography/p27.png",
    gsm: "300 GSM",
    fabric: "Heavy Interlock Knit",
    color: "Pitch Black / Crimson / Cobalt Accents",
    edition: "Drop 001 // Edition of 200",
    description:
      "Pure momentum. Strike-through typography and coordinate side-bars engineered for high-speed city navigation.",
    details: [
      "300 GSM heavyweight knit",
      "Cobalt technical globe icons on lower chest",
      "Extended wrist ribbing that stays locked during movement",
      "Double-needle bottom hem",
    ],
    inStock: true,
  },
  {
    id: "em-04",
    name: "COMPASS & CHAINS TEE",
    slug: "compass-chains-tee",
    collection: "emotions",
    category: "tee",
    price: 85,
    image: "/assets/photography/p8.png",
    lifestyleImage: "/assets/photography/p25.png",
    gsm: "280 GSM",
    fabric: "100% Combed Cotton",
    color: "Aged Charcoal Black / Weathered Silver",
    edition: "Drop 001 // Kinetic Core",
    description:
      "Direction over hesitation. Weathered Gothic Emotions typography with 3D chrome nautical compass and broken chainlinks.",
    details: [
      "280 GSM vintage wash cotton",
      "Distressed metallic silver and crimson brush stroke script",
      "Lower crest emblem: 'MOTION OVER EVERYTHING'",
      "Reinforced neck tape",
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "em-05",
    name: "COMPASS & CHAINS HOODIE",
    slug: "compass-chains-hoodie",
    collection: "emotions",
    category: "hoodie",
    price: 175,
    image: "/assets/photography/p9.png",
    lifestyleImage: "/assets/photography/p28.png",
    gsm: "450 GSM",
    fabric: "Heavyweight French Terry",
    color: "Void Black / Chrome Silver / Crimson",
    edition: "Drop 001 // Limited Run",
    description:
      "The kinetic flagship. Built to withstand friction with an oversized hood and massive central graphic treatment.",
    details: [
      "450 GSM premium cotton fleece",
      "Dense 6-color screenprint with metallic silver pigment",
      "Oversized streetwear drape",
      "Custom woven collection neck label",
    ],
    inStock: true,
    featured: true,
  },
  {
    id: "em-06",
    name: "PRESSURE DIRECTION CREWNECK",
    slug: "pressure-direction-crewneck",
    collection: "emotions",
    category: "longsleeve",
    price: 145,
    image: "/assets/photography/p10.png",
    lifestyleImage: "/assets/photography/p27.png",
    gsm: "400 GSM",
    fabric: "Diagonal Loopback Cotton",
    color: "Onyx Black / Steel / Crimson",
    edition: "Drop 001 // Edition of 200",
    description:
      "Raw propulsion. Heavyweight crewneck sweater featuring Gothic distressed lettering and industrial chain motif.",
    details: [
      "400 GSM loopback cotton",
      "Collar, cuffs, and hem in durable 2x2 rib",
      "Drop-shoulder construction with relaxed chest",
      "Zero emotion graphic manifesto",
    ],
    inStock: true,
  },
  {
    id: "em-07",
    name: "MOTION DUOLOGY CAPSULE 001",
    slug: "motion-duology-capsule-001",
    collection: "emotions",
    category: "capsule",
    price: 340,
    originalPrice: 420,
    image: "/assets/photography/p28.png",
    lifestyleImage: "/assets/photography/p28.png",
    gsm: "Multi-GSM",
    fabric: "Three Apes French Terry & Heavy Cotton Duology",
    color: "Void Black / High-Voltage Crimson",
    edition: "Collector Duology Set // 50 Units",
    description:
      "The definitive Emotions dual release: Includes the Three Apes Velocity Hoodie (450 GSM), Three Apes Heavyweight Tee (280 GSM), and collector sticker kit.",
    details: [
      "1x Three Apes Velocity Hoodie (450 GSM)",
      "1x Three Apes Oversized Tee (280 GSM)",
      "1x Compass & Chains Graphic Bandana",
      "Numbered metallic foil certificate",
    ],
    inStock: true,
  },
];

export const EDITORIAL_ASSETS = {
  heroCheckmate: "/assets/photography/p22.png",
  heroEmotions: "/assets/photography/p24.png",
  latestDropBanner: "/assets/photography/p20.png",
  streetwearDuo: "/assets/photography/p23.png",
  concreteModel: "/assets/photography/p21.png",
  architecturalFullBody: "/assets/photography/p19.png",
  capsuleShowroom: "/assets/photography/p18.png",
  logoWhite: "/assets/logo/logo-white.png",
};
